name: Deploy
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs-build:
    name: Build documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: docs/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build docs
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/.vitepress/dist"

  docs-deploy:
    name: Deploy documentation
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: docs-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  bundle:
    name: Bundle
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
      - name: Build Solution
        run: dotnet build -c Release
      - name: Build Debug Solution
        run: dotnet build -c Debug
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: StreamerBotToolsBundle
          path: ./StreamerBotTools/bin
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: StreamerBotTools/bin/Release/StreamerBotTools.dll
